definitions:
  handler.APIResponse:
    properties:
      data:
        description: 응답 데이터
      error:
        description: 에러 메시지
        type: string
      message:
        description: 응답 메시지
        type: string
      success:
        description: 요청 성공 여부
        type: boolean
    type: object
  handler.CalculatorRequest:
    properties:
      operand1:
        description: 첫번째 피연산자
        type: number
      operand2:
        description: 두번째 피연산자
        type: number
      operation:
        description: 수행할 연산 (add, subtract, multiply, divide)
        type: string
    type: object
  handler.CalculatorResponse:
    properties:
      operand1:
        description: 첫 번째 피연산자
        type: number
      operand2:
        description: 두 번째 피연산자
        type: number
      operation:
        description: 수행된 연산
        type: string
      result:
        description: 계산 결과
        type: number
    type: object
info:
  contact: {}
paths:
  /api/calculator/calculate:
    post:
      consumes:
      - application/json
      description: 두 숫자에 대한 사칙연산을 수행합니다.
      parameters:
      - description: 계산 요청
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.CalculatorRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 계산 성공
          schema:
            allOf:
            - $ref: '#/definitions/handler.APIResponse'
            - properties:
                data:
                  $ref: '#/definitions/handler.CalculatorResponse'
              type: object
        "400":
          description: 잘못된 요청
          schema:
            $ref: '#/definitions/handler.APIResponse'
        "405":
          description: 허용되지 않는 HTTP 메서드
          schema:
            $ref: '#/definitions/handler.APIResponse'
      summary: 계산기 계산 수행
      tags:
      - Calculator
  /api/calculator/history:
    delete:
      description: 모든 계산 히스토리를 삭제합니다.
      produces:
      - application/json
      responses:
        "200":
          description: 히스토리 초기화 성공
          schema:
            $ref: '#/definitions/handler.APIResponse'
        "405":
          description: 허용되지 않는 HTTP 메서드
          schema:
            $ref: '#/definitions/handler.APIResponse'
      summary: 계산기 히스토리 초기화
      tags:
      - Calculator
    get:
      description: 수행된 모든 계산의 히스토리를 조회합니다.
      produces:
      - application/json
      responses:
        "200":
          description: 히스토리 조회 성공
          schema:
            allOf:
            - $ref: '#/definitions/handler.APIResponse'
            - properties:
                data:
                  items:
                    additionalProperties: true
                    type: object
                  type: array
              type: object
        "405":
          description: 허용되지 않는 HTTP 메서드
          schema:
            $ref: '#/definitions/handler.APIResponse'
      summary: 계산기 히스토리 조회
      tags:
      - Calculator
  /api/calculator/stats:
    get:
      description: 계산기 사용 통계 정보를 조회합니다.
      produces:
      - application/json
      responses:
        "200":
          description: 통계 조회 성공
          schema:
            allOf:
            - $ref: '#/definitions/handler.APIResponse'
            - properties:
                data:
                  additionalProperties: true
                  type: object
              type: object
        "405":
          description: 허용되지 않는 HTTP 메서드
          schema:
            $ref: '#/definitions/handler.APIResponse'
      summary: 계산기 통계 조회
      tags:
      - Calculator
swagger: "2.0"
